import Head from "next/head";
import NavBar from "@/components/NavBar";
import HomePage from "@/components/HomePage";
import About from "@/components/About";
import Skills from "@/components/skills/Skills";
import Project from "@/components/projects/Projects";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portafolio | front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      <About />
      <Skills />
      <Project />
      <Contact />
    </div>
  );
}
